//autogenerated by ./perm2js from ./contracts/PermissionsLevel.sol
let permissions = {
    CanSpend: 1 << 0,
    CanUnfreeze: 1 << 1,
    CanChangeParticipants: 1 << 2,
    CanChangeBypass: 1 << 3,
    CanSignBoosts: 1 << 4,
    CanExecuteBoosts: 1 << 5,
    CanFreeze: 1 << 6,
    CanCancelConfigChanges: 1 << 7,
    CanCancelSpend: 1 << 8,
    CanApprove: 1 << 9,
    CanAddOperator: 1 << 10,
    CanExecuteBypassCall: 1 << 11,
    CanCancelBypassCall: 1 << 12,
    CanSetAcceleratedCalls: 1 << 13,
    CanSetAddOperatorNow: 1 << 14,
    CanAddOperatorNow: 1 << 15,
}

let canCancel = permissions.CanCancelSpend | permissions.CanCancelConfigChanges | permissions.CanCancelBypassCall
let canChangeConfig = permissions.CanUnfreeze | permissions.CanChangeParticipants | permissions.CanAddOperator | permissions.CanAddOperatorNow | permissions.CanChangeBypass | permissions.CanSetAcceleratedCalls | permissions.CanSetAddOperatorNow
let ownerPermissions = (permissions.CanSpend | canCancel | permissions.CanFreeze | canChangeConfig | permissions.CanSignBoosts | permissions.CanExecuteBypassCall)
let adminPermissions = permissions.CanExecuteBoosts | permissions.CanAddOperator
let watchdogPermissions = canCancel | permissions.CanFreeze | permissions.CanApprove

Object.assign(permissions, {
    CanChangeConfig: canChangeConfig,
    CanCancel: canCancel,
    OwnerPermissions: ownerPermissions,
    AdminPermissions: adminPermissions,
    WatchdogPermissions: watchdogPermissions,
});

module.exports = Object.freeze(permissions);